version: "3"

services:
  ohmyzsh:
    image: ohmyzsh/zsh:latest
    container_name: ohmyzsh
    tty: true
    volumes:
    - .:/root/persi-zsh-theme
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    command: /usr/bin/zsh
